### ISSUE TITLE
YAML is not supported for template import

### ISSUE THREAD

**Issue by ThisIsTenou** [StowasserH/ccu3values#1]
Hey there, I can't seem to be able to import .yaml templates into my zabbix 5.0 LTS instance. It only accepts XML templates. Is there a chance you could re-export it as xml?

Thank you for your work, I'm very much looking forward to implementing it! Have a great day and stay safe :)

**Comment by StowasserH** [comment]
Unfortunately, I've only now seen the issu. I have now added the template as xml. Hopefully not too late.
Kind regards, Harald.

**Comment by ThisIsTenou** [comment]
Haha, all good! I gotta admit that I've made my own project in the meantime for my limited usecase: https://github.com/ThisIsTenou/zabbix-homematic-monitoring

I'll still give yours a shot sometime though, now I'm really intrigued how it works!
